const SOURCES={pals:'https://raw.githubusercontent.com/helios57/palworld/main/data/pals.json',special:'https://raw.githubusercontent.com/helios57/palworld/main/data/special_combos.json',idmap:'https://raw.githubusercontent.com/helios57/palworld/main/data/internal_id_map.json',paldata:'https://raw.githubusercontent.com/KrisCris/Palworld-Pal-Editor/develop/src/palworld_pal_editor/assets/data/pal_data.json',passives:'https://raw.githubusercontent.com/KrisCris/Palworld-Pal-Editor/develop/src/palworld_pal_editor/assets/data/pal_passives.json'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFKC').replace(/[\u3041-\u3096]/g,ch=>String.fromCharCode(ch.charCodeAt(0)+0x60)).toLowerCase().trim();
let eng=null,currentTarget=null,currentSteps=[];
let owned={counts:new Map(),genders:new Map(),individuals:[],meta:{}};
function gRec(n){if(!owned.genders.has(n))owned.genders.set(n,{Male:0,Female:0,Other:0});return owned.genders.get(n)}
async function getJson(url){const r=await fetch(url,{cache:'no-cache'});if(!r.ok)throw new Error(`${r.status}: ${url}`);return r.json()}
class Engine{
 constructor(palsObj,specials,idmap,palData,passiveData){
  this.info={};for(const[n,d]of Object.entries(palsObj)){if(d?.combi_rank===undefined)continue;this.info[n]={deck:String(d.paldeck??''),rank:Number(d.combi_rank),generic:Boolean(d.in_generic_pool)}}
  this.names=Object.keys(this.info);this.generic=this.names.filter(n=>this.info[n].generic);this.idmap=idmap||{};this.special=new Map();
  for(const c of specials||[]){if(c?.parent_a&&c?.parent_b&&c?.child)this.special.set(this.key(c.parent_a,c.parent_b),c.child)}
  this.jpByDeck={};for(const rec of Object.values(palData||{})){if(!rec?.I18n?.ja||!rec?.PaldeckIndex)continue;const deck=`${rec.PaldeckIndex}${rec.PaldeckSuffix||''}`;if(!this.jpByDeck[deck]||rec.RegularlyObtainable===true||rec.Invalid===false)this.jpByDeck[deck]=rec.I18n.ja}
  this.passives={};for(const[id,rec]of Object.entries(passiveData||{}))this.passives[id]={name:rec?.I18n?.ja?.Name||rec?.I18n?.en?.Name||id};this.cache=new Map();this.parentsCache=new Map();
 }
 key(a,b){return[a,b].sort().join('\0')}
 jp(n){return this.jpByDeck[this.info[n]?.deck]||n}
 label(n){const d=this.info[n];return d?.deck?`${this.jp(n)} #${d.deck}`:this.jp(n)}
 passiveName(id){return this.passives[id]?.name||id}
 result(a,b){const k=this.key(a,b);if(this.cache.has(k))return this.cache.get(k);let c;if(a===b)c=a;else if(this.special.has(k))c=this.special.get(k);else{const target=Math.floor((this.info[a].rank+this.info[b].rank+1)/2);let best=null;c=null;for(const n of this.generic){const s=[Math.abs(this.info[n].rank-target),-this.info[n].rank,n];if(!best||s[0]<best[0]||(s[0]===best[0]&&(s[1]<best[1]||(s[1]===best[1]&&s[2]<best[2])))){best=s;c=n}}}this.cache.set(k,c);return c}
 resolve(q){q=norm(q);if(!q)return null;let hit=this.names.find(n=>[n,this.jp(n),this.info[n].deck,`#${this.info[n].deck}`,this.label(n)].some(x=>norm(x)===q));if(hit)return hit;const xs=this.names.filter(n=>norm(`${n} ${this.jp(n)} ${this.info[n].deck}`).includes(q));xs.sort((a,b)=>this.jp(a).localeCompare(this.jp(b),'ja'));return xs[0]||null}
 internalToName(raw){for(const c of[raw,raw.replace(/^BOSS_/,''),raw.replace(/^RAID_/,''),raw.replace(/^GYM_/,''),raw.replace(/_Tower$/,'')]){const n=this.idmap[c];if(n&&this.info[n])return n}return null}
 parentsFor(target){if(this.parentsCache.has(target))return this.parentsCache.get(target);const out=[];for(let i=0;i<this.names.length;i++)for(let j=i;j<this.names.length;j++){const a=this.names[i],b=this.names[j];if(this.result(a,b)===target)out.push([a,b])}this.parentsCache.set(target,out);return out}
 shortest(ownedSet,target,maxRounds=8){const score=new Map(),via=new Map();for(const n of ownedSet)score.set(n,[0,0]);for(let r=0;r<maxRounds;r++){const avail=[...score.keys()],cand=new Map();for(let i=0;i<avail.length;i++)for(let j=i;j<avail.length;j++){const a=avail[i],b=avail[j],c=this.result(a,b),sa=score.get(a),sb=score.get(b),ready=(ownedSet.has(a)&&ownedSet.has(b)&&statusFor(a,b)==='すぐ可能')?0:1,s=[Math.max(sa[0],sb[0])+1,sa[1]+sb[1]+ready+1],cur=score.get(c),p=cand.get(c);if((!cur||cmp(s,cur)<0)&&(!p||cmp(s,p.s)<0))cand.set(c,{s,a,b})}let ch=false;for(const[c,v]of cand){if(!score.has(c)||cmp(v.s,score.get(c))<0){score.set(c,v.s);via.set(c,[v.a,v.b]);ch=true}}if(score.has(target)&&r>0)break;if(!ch)break}return{score,via}}
 flatten(target,ownedSet,via){const out=[],done=new Set();const visit=x=>{if(ownedSet.has(x)||done.has(x)||!via.has(x))return;const[a,b]=via.get(x);visit(a);visit(b);out.push([a,b,x]);done.add(x)};visit(target);return out}
}
function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]??0,y=b[i]??0;if(x<y)return-1;if(x>y)return 1}return 0}
async function init(){try{$('#dataStatus').textContent='公開データ取得中…';const[p,s,i,d,ps]=await Promise.all(Object.values(SOURCES).map(getJson));eng=new Engine(p,s,i,d,ps);$('#dataStatus').textContent=`OK・${eng.names.length}種`;const dl=$('#palOptions');for(const n of[...eng.names].sort((a,b)=>eng.jp(a).localeCompare(eng.jp(b),'ja'))){const o=document.createElement('option');o.value=eng.label(n);dl.appendChild(o)}$('#targetResolved').textContent='目的パルを入力してください。';refreshButtons()}catch(e){showError('ゲームデータ取得失敗\n'+e.message);$('#dataStatus').textContent='取得失敗'}}
function showError(msg){const b=$('#errorBox');b.textContent=msg;b.classList.remove('hidden')}function clearError(){$('#errorBox').classList.add('hidden')}
function refreshButtons(){const ok=Boolean(eng&&owned.individuals.length);$('#searchBtn').disabled=!ok;$('#reverseBtn').disabled=!ok}
async function loadOwnedFile(file){clearError();try{if(!eng)throw new Error('ゲームデータの読み込み完了後に選択してください。');const data=JSON.parse(await file.text());if(data.schema!=='palbreeder-owned-pals-v1')throw new Error('Reader v2.7 の owned_pals.json を選択してください。');owned={counts:new Map(),genders:new Map(),individuals:[],meta:{...(data.player||{}),generated_at:data.generated_at||''}};for(const[idx,r]of(data.pals||[]).entries()){const n=eng.internalToName(String(r.internal_id||''));if(!n)continue;owned.counts.set(n,(owned.counts.get(n)||0)+1);const g=gRec(n),sex=String(r.gender||'');if(sex==='Male'||sex==='Female')g[sex]++;else g.Other++;owned.individuals.push({row:idx+1,species:n,gender:sex,level:r.level||'',nickname:r.nickname||'',passives:(r.passive_skill_ids||[]).map(String)})}$('#playerName').textContent=`${owned.meta.nickname||'不明'}${owned.meta.level?` Lv.${owned.meta.level}`:''}`;$('#ownedSummary').textContent=`${owned.individuals.length}体 / ${owned.counts.size}種`;$('#updatedAt').textContent=owned.meta.generated_at||'不明';renderOwned();refreshButtons();$('#routeNote').textContent='目的パルを指定して検索してください。'}catch(e){showError(e.message)}}
function statusFor(a,b){const ca=owned.counts.get(a)||0,cb=owned.counts.get(b)||0,ga=gRec(a),gb=gRec(b);if(!ca&&!cb)return'両方未所持';if(!ca||!cb)return'片方未所持';if(a===b){if(ca<2)return'同種2体目が必要';if(ga.Male&&ga.Female)return'すぐ可能';return(ga.Male+ga.Female)?'性別が合わない':'性別要確認'}if((ga.Male&&gb.Female)||(ga.Female&&gb.Male))return'すぐ可能';if((ga.Male+ga.Female)&&(gb.Male+gb.Female))return'性別が合わない';return'性別要確認'}
function stateClass(s){return s==='すぐ可能'?'state-good':(s.includes('未所持')||s.includes('必要')||s.includes('合わない'))?'state-bad':'state-warn'}
function resolveTarget(){if(!eng)return null;currentTarget=eng.resolve($('#targetInput').value);$('#targetResolved').textContent=currentTarget?`選択: ${eng.label(currentTarget)}`:'一致するパルが見つかりません。';return currentTarget}
function renderRoute(){const target=resolveTarget();if(!target)return;const ownedSet=new Set(owned.counts.keys()),{score,via}=eng.shortest(ownedSet,target);currentSteps=eng.flatten(target,ownedSet,via);if(ownedSet.has(target)){$('#routeNote').textContent=`${eng.label(target)} はすでに所持しています。`;$('#routeBadge').textContent='所持済み';$('#routeBody').innerHTML=''}else if(!score.has(target)||!currentSteps.length){$('#routeNote').textContent='現在の所持パルだけからのルートは見つかりませんでした。';$('#routeBadge').textContent='未検出';$('#routeBody').innerHTML=''}else{$('#routeBadge').textContent=`${currentSteps.length}手順`;$('#routeNote').textContent=`最短世代 ${score.get(target)[0]} / 配合操作 ${currentSteps.length}回`;$('#routeBody').innerHTML=currentSteps.map(([a,b,c],i)=>{const st=ownedSet.has(a)&&ownedSet.has(b)?statusFor(a,b):'前段の完成待ち';return`<tr><td>${i+1}</td><td>${esc(eng.label(a))}</td><td>${esc(eng.label(b))}</td><td><strong>${esc(eng.label(c))}</strong></td><td class="${stateClass(st)}">${esc(st)}</td></tr>`}).join('')}renderDirect(target);renderRequired(currentSteps,ownedSet);renderFlow(target,currentSteps,ownedSet)}
function renderDirect(target){const pairs=eng.parentsFor(target),rank=s=>({'すぐ可能':0,'性別要確認':1,'性別が合わない':2,'片方未所持':3,'同種2体目が必要':4,'両方未所持':5}[s]??9),rows=pairs.map(([a,b])=>[a,b,statusFor(a,b)]).sort((x,y)=>rank(x[2])-rank(y[2]));$('#directBody').innerHTML=rows.map(([a,b,s])=>`<tr><td>${esc(eng.label(a))}</td><td>${esc(eng.label(b))}</td><td class="${stateClass(s)}">${esc(s)}</td></tr>`).join('');const os=new Set(owned.counts.keys()),one=[];for(const[a,b]of pairs){if(a===b)continue;const ao=os.has(a),bo=os.has(b);if(ao!==bo){const have=ao?a:b,need=ao?b:a;one.push([have,need])}}$('#oneMissingBody').innerHTML=one.map(r=>`<tr><td>${esc(eng.label(r[0]))}</td><td>${esc(eng.label(r[1]))}</td></tr>`).join('')}
function renderRequired(steps,os){const req=[];for(const[a,b]of steps){if(!os.has(a)||!os.has(b))continue;const st=statusFor(a,b);if(st==='同種2体目が必要')req.push([a,'同種配合に2体必要']);else if(st==='性別が合わない'){req.push([a,'逆性別の個体を追加候補']);req.push([b,'逆性別の個体を追加候補'])}else if(st==='性別要確認'){req.push([a,'性別確認']);req.push([b,'性別確認'])}}const m=new Map();for(const x of req)m.set(x.join('|'),x);$('#requiredBody').innerHTML=[...m.values()].map(([n,r])=>`<tr><td>${esc(eng.label(n))}</td><td>${esc(r)}</td></tr>`).join('')||'<tr><td colspan="2" class="muted">現時点で追加条件はありません。</td></tr>'}
function genderText(n,generated=false){if(generated)return'孵化後に性別選別';const g=gRec(n);return`♂${g.Male} / ♀${g.Female}${g.Other?` / ?${g.Other}`:''}`}
function renderFlow(target,steps,os){const svg=$('#flowSvg'),detail=$('#flowDetail');svg.innerHTML='';if(!target||(!steps.length&&!os.has(target))){svg.setAttribute('viewBox','0 0 700 220');svg.innerHTML='<text x="40" y="80" fill="#445" font-size="18">表示できるルートがありません。</text>';return}const via=new Map(),stepNo=new Map();steps.forEach((s,i)=>{via.set(s[2],[s[0],s[1]]);stepNo.set(s[2],i+1)});const all=new Set([target]);steps.forEach(s=>s.forEach(x=>all.add(x)));const dm=new Map(),depth=x=>{if(dm.has(x))return dm.get(x);if(!via.has(x)){dm.set(x,0);return 0}const[a,b]=via.get(x),d=Math.max(depth(a),depth(b))+1;dm.set(x,d);return d};let leaf=0;const om=new Map(),order=x=>{if(om.has(x))return om.get(x);if(!via.has(x)){om.set(x,leaf++);return om.get(x)}const[a,b]=via.get(x),v=(order(a)+order(b))/2;om.set(x,v);return v};order(target);const boxW=210,boxH=78,colGap=300,rowGap=120,left=50,top=70,pos=new Map();let maxD=0,maxY=0;for(const n of all){const d=depth(n),y=top+order(n)*rowGap,x=left+d*colGap;pos.set(n,[x,y]);maxD=Math.max(maxD,d);maxY=Math.max(maxY,y)}const W=left+(maxD+1)*colGap+boxW+50,H=Math.max(300,maxY+boxH+60);svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('width',W);svg.setAttribute('height',H);svg.innerHTML='<defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#657080"/></marker></defs>';for(const[to,ps]of via){for(const p of ps){const[x1,y1]=pos.get(p),[x2,y2]=pos.get(to),sx=x1+boxW,sy=y1+boxH/2,ex=x2,ey=y2+boxH/2,mx=(sx+ex)/2;svg.insertAdjacentHTML('beforeend',`<path d="M${sx} ${sy} H${mx} V${ey} H${ex}" fill="none" stroke="#657080" stroke-width="1.5" marker-end="url(#arrow)"/>`)}}for(const n of all){const[x,y]=pos.get(n),goal=n===target,generated=via.has(n),ownedFlag=os.has(n),fill=goal?'#ffe28a':ownedFlag?'#ccebd6':generated?'#cfe1fa':'#f3cccc',status=ownedFlag?'所持':generated?'途中で作成':'未所持';const id='n'+Math.random().toString(36).slice(2);svg.insertAdjacentHTML('beforeend',`<g id="${id}" tabindex="0"><rect x="${x}" y="${y}" width="${boxW}" height="${boxH}" rx="10" fill="${fill}" stroke="#607080"/><text x="${x+10}" y="${y+22}" fill="#17202a" font-size="13" font-weight="700">${esc(eng.label(n))}</text><text x="${x+10}" y="${y+44}" fill="#2e3b47" font-size="11">${esc(status)}${stepNo.get(n)?` / 手順 ${stepNo.get(n)}`:''}</text><text x="${x+10}" y="${y+63}" fill="#4c5a67" font-size="10">${esc(genderText(n,generated))}</text></g>`);svg.querySelector('#'+id).addEventListener('click',()=>{const g=gRec(n),pass=[...new Set(owned.individuals.filter(x=>x.species===n).flatMap(x=>x.passives))].map(x=>eng.passiveName(x));detail.innerHTML=`<h3>${esc(eng.label(n))}</h3><p>状態: ${esc(status)}</p><p>所持数: ${owned.counts.get(n)||0}体</p><p>♂${g.Male} / ♀${g.Female} / ?${g.Other}</p><p class="muted">${esc(pass.join(' / ')||'パッシブ情報なし')}</p>`})}}
function exportPng(){const svg=$('#flowSvg'),vb=svg.viewBox.baseVal;if(!vb.width)return;const data=new XMLSerializer().serializeToString(svg.cloneNode(true)),blob=new Blob([data],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const scale=2,c=document.createElement('canvas');c.width=vb.width*scale;c.height=vb.height*scale;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.scale(scale,scale);ctx.drawImage(img,0,0);URL.revokeObjectURL(url);c.toBlob(p=>{const a=document.createElement('a');a.href=URL.createObjectURL(p);a.download='palbreeder-flow.png';a.click()})};img.src=url}
function renderReverse(){const parent=eng.resolve($('#reverseInput').value);if(!parent)return;const partners=$('#ownedPartnersOnly').checked?[...owned.counts.keys()].filter(x=>eng.info[x]):eng.names;const rows=partners.map(p=>[p,eng.result(parent,p),owned.counts.has(p)?'所持':'未所持']).sort((a,b)=>eng.jp(a[1]).localeCompare(eng.jp(b[1]),'ja'));$('#reverseBody').innerHTML=rows.map(r=>`<tr><td>${esc(eng.label(r[0]))}</td><td>${esc(eng.label(r[1]))}</td><td>${r[2]}</td></tr>`).join('')}
function renderOwned(){
 const filter=$('#ownedFilter'),q=norm(filter?.value||''),rows=[];
 if(!eng)return;
 for(const[n,count]of owned.counts){
  if(q&&!norm(`${eng.jp(n)} ${n}`).includes(q))continue;
  const g=gRec(n),individuals=owned.individuals.filter(x=>x.species===n),pass=[...new Set(individuals.flatMap(x=>x.passives))].map(x=>eng.passiveName(x));
  rows.push({n,count,g,pass,individuals});
 }
 rows.sort((a,b)=>eng.jp(a.n).localeCompare(eng.jp(b.n),'ja'));
 $('#ownedBody').innerHTML=rows.map(({n,count,g,pass})=>`<tr><td>${esc(eng.label(n))}</td><td>${count}</td><td>${g.Male}</td><td>${g.Female}</td><td>${g.Other}</td><td>${esc(pass.join(' / '))}</td></tr>`).join('');
 const summary=$('#ownedListSummary'),list=$('#ownedList');
 if(!summary||!list)return;
 const totalGender=[...owned.genders.values()].reduce((sum,g)=>({Male:sum.Male+g.Male,Female:sum.Female+g.Female,Other:sum.Other+g.Other}),{Male:0,Female:0,Other:0});
 summary.textContent=`${owned.individuals.length}体 / ${owned.counts.size}種 / ♂${totalGender.Male}・♀${totalGender.Female}${totalGender.Other?`・不明${totalGender.Other}`:''}${q?` / 表示${rows.length}種`:''}`;
 list.innerHTML=rows.length?rows.map(({n,count,g,pass,individuals})=>{
  const chips=pass.slice(0,3).map(name=>`<span class="owned-passive-chip">${esc(name)}</span>`).join('')+(pass.length>3?`<span class="owned-passive-chip more">+${pass.length-3}</span>`:'');
  const detail=individuals.map((x,i)=>{const sex=x.gender==='Male'?'♂':x.gender==='Female'?'♀':'?';const names=[...new Set(x.passives)].map(id=>eng.passiveName(id));return`<div class="owned-individual"><div><strong>${esc(x.nickname||`個体 ${i+1}`)}</strong><span>${esc(`${sex}${x.level?` / Lv.${x.level}`:''}`)}</span></div><p>${esc(names.join(' / ')||'パッシブ情報なし')}</p></div>`}).join('');
  return`<details class="owned-item"><summary><div class="owned-summary-main"><div class="owned-name-row"><strong>${esc(eng.label(n))}</strong><span>${count}体</span></div><div class="owned-gender-row">♂${g.Male}　♀${g.Female}${g.Other?`　不明${g.Other}`:''}</div><div class="owned-passive-chips">${chips||'<span class="owned-no-passive">パッシブ情報なし</span>'}</div></div></summary><div class="owned-individuals">${detail}</div></details>`;
 }).join(''):'<div class="owned-list-empty">一致する所持パルがありません。</div>';
}
$('#fileInput').addEventListener('change',e=>e.target.files[0]&&loadOwnedFile(e.target.files[0]));for(const ev of['dragenter','dragover'])$('#dropZone').addEventListener(ev,e=>e.preventDefault());$('#dropZone').addEventListener('drop',e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)loadOwnedFile(f)});$('#targetInput').addEventListener('input',resolveTarget);$('#searchBtn').addEventListener('click',renderRoute);$('#reverseBtn').addEventListener('click',renderReverse);$('#ownedFilter').addEventListener('input',renderOwned);$('#pngBtn').addEventListener('click',exportPng);$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#tab-${b.dataset.tab}`).classList.add('active')}));
init();
